config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  devise_for :users,
  				path: '',
  				path_names: {sign_in: 'login', sign_out: 'logout', edit: 'profile', sign_up: 'registration'},
  				controllers: {omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations'}

  resources :users, only: [:show]
  resources :rooms, except: [:edit] do
    member do
      get 'listing'
      get 'pricing'
      get 'description'
      get 'photo_upload'
      get 'amenities'
      get 'location'
      delete 'delete_image'
    end
    resources :images, only: [:create, :destroy]
    resources :reservations, only: [:create]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :user
  has_many_attached :images
  has_many :reservations

  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  validates :home_type, presence: true
  validates :room_type, presence: true
  validates :accomodate, presence: true
  validates :bed_room, presence: true
  validates :bath_room, presence: true

  def cover_photo
  	if self.images.length > 0
  		self.images[0]
	else
		"blank.jpg"
	end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable, :omniauthable

  validates :fullname, presence: true, length: {maximum: 50}
  has_one_attached :avatar

  has_many :rooms
  has_many :reservations

  def self.from_omniauth(auth)
  	  user = User.where(email: auth.info.email).first

  	  if user
  	  	return user
  	  else

	  where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
	    user.email = auth.info.email
	    user.password = Devise.friendly_token[0, 20]
	    user.fullname = auth.info.name
	    user.image = auth.info.image
	    user.uid = auth.uid
	    user.provider = auth.provider
	    # If you are using confirmable and the provider(s) you use validate emails, 
	    # uncomment the line below to skip the confirmation emails.
	    user.skip_confirmation!
	  end
	end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception

	before_action :configure_permitted_parameters, if: :devise_controller?

	protected

	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:sign_up, keys: [:fullname, :avatar, :phone_number, :description])
		devise_parameter_sanitizer.permit(:account_update, keys: [:fullname, :avatar, :phone_number, :description])
	end

end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
	protected
		def update_resource(resource, params)
			resource.update_without_password(params)
		end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
	before_action :authenticate_user!


	def create
		room = Room.find(params[:room_id])

		if current_user == room.user
			flash[:alert] = "You cannot book your own property!"
		else
			start_date = Date.parse(reservations_params[:start_date])
			end_date = Date.parse(reservations_params[:end_date])
			days = (end_date - start_date).to_i + 1

			@reservation = current_user.reservations.build(reservations_params)
			@reservation.room = room
			@reservation.price = room.price
			@reservation.total = room.price * days
			@reservation.save

			flash[:notice] = "Booked Successfully!"
		end
		redirect_to room
	end

	private
		def reservations_params
			params.require(:reservation).permit(:start_date, :end_date)
		end
end

app/controllers/room_controller.rb
class RoomController < ApplicationController
  
  before_action :set_room, except: [:index, :new, :create]
  before_action :authenticate_user!, except: [:show]

  def index
    @rooms = current_user.rooms
  end

  def new
    @room = current_user.rooms.build
  end

  def create
    @room = current_user.rooms.build(room_params)
    if @room.save
      redirect_to listing_room_path(@room), notice: "Saved..."
    else
      render :new, notice: "Something went wrong"
    end
  end

  def show
  end

  def listing
  end

  def pricing
  end

  def description
  end

  def photo_upload
  end

  def amenities
  end

  def location
  end

  def update
    if @room.update(room_params)
      flash[:notice] = "Saved"
    else
      flash[:notice] = "Something went wrong"
    end
    redirect_back(fallback_location: request.referer)
  end

  private
    def set_room
      @room = Room.find(params[:id])
    end

    def room_params
      params.require(:room).permit(:home_type, :room_type, :accomodate, :bed_room, :bath_room, :listing_name, :summary, :address, :is_tv, :is_kitchen, :is_air, :is_heating, :is_internet, :price, :active)
    end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  
  before_action :set_room, except: [:index, :new, :create, :delete_image]
  before_action :authenticate_user!, except: [:show]

  def index
    @rooms = current_user.rooms
  end

  def new
    @room = current_user.rooms.build
  end

  def create
    @room = current_user.rooms.build(room_params)
    if @room.save
      redirect_to listing_room_path(@room), notice: "Saved..."
    else
      flash[:alert] = "Please complete all fields"
      render :new
    end
  end

  def show
  end

  def listing
  end

  def pricing
  end

  def description
  end

  def photo_upload
  end

  def amenities
  end

  def location
  end

  def delete_image
    @images = ActiveStorage::Attachment.find(params[:id])
    @images.purge
    redirect_back(fallback_location: request.referer)
  end

  def update

    new_params = room_params
    new_params = room_params.merge(active: true) if is_ready_room
    
    if @room.update(new_params)
      flash[:notice] = "Saved"
    else
      flash[:alert] = "Something went wrong"
    end
    redirect_back(fallback_location: request.referer)
  end

  private
    def set_room
      @room = Room.find(params[:id])
    end

    def is_authorised
      redirect_to root_path, alert: "You don't have permission" unless current_user.id == @room.user_id
    end

    def is_ready_room
      !@room.active && !@room.price.blank? && !@room.listing_name.blank? && !@room.images.blank? && !@room.address.blank?
    end

    def room_params
      params.require(:room).permit(:home_type, :room_type, :accomodate, :bed_room, :bath_room, :listing_name, :summary, :address, :is_tv, :is_kitchen, :is_air, :is_heating, :is_internet, :price, :active, images: [])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def show
		@user = User.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def avatar_url(user)
		if user.image
			user.avatar="http://graph.facebook.com/#{user.uid}/picture?type=large"
		end
	end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/room_helper.rb
module RoomHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pikachu</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Varela+Round&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">
    <link rel="stylesheet" href="http://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">

  </head>

  <body>

    <%= render 'shared/navbar' %>
    <%= render 'shared/message' %>

  <div class="container">
    <%= yield %>
  </div>

  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/reservations/_form.html.erb
<div class="panel panel-default">
	<div class="panel-heading">
		<span><i class="fa fa-bolt" style="color: #ffb400"></i>$<%= @room.price %></span>
		<span class="pull-right">Per Night</span>
	</div>
	<div class="panel-body">
		
		<%= form_for([@room, @room.reservations.new]) do |f| %>
			<div class="row">
				<div class="col-md-6">
					<label>Pick Up</label>
					<%= f.text_field :start_date, readonly: true, placeholder: "Start date...", class: "form-control datepicker", autocomplete: "off" %>
				</div>
				<div class="col-md-6">
					<label>Drop Off</label>
					<%= f.text_field :end_date, readonly: true, placeholder: "End date...", class: "form-control datepicker", autocomplete: "off", disabled: true %>
				</div>
			</div>

			<div id="preview" style="display: none">
				<table class="reservation-table">
					<tbody>
						<tr>
							<td>Price</td>
							<td class="text-right">$<%= @room.price %></td>
						</tr>
						<tr>
							<td>Night(s)</td>
							<td class="text-right"><span id="reservation-days"></span></td>
						</tr>
						<tr>
							<td class="total">Total</td>
							<td class="text-right">$<span id="reservation-total"></span></td>
						</tr>
					</tbody>
				</table>
			</div>
			<br/>
			<%= f.submit "Book Now", class: "btn btn-normal btn-block" %>
		<% end %>
	</div>
</div>

<script>
	$(function(){
		$('#reservation_start_date').datepicker({
			dateFormat: 'dd-mm-yy'
		});
		$('#reservation_end_date').datepicker({
			dateFormat: 'dd-mm-yy'
		});
	});
</script>

app/views/rooms/_photos_list.html.erb
<br/>
<div class="row">

	<% @room.images.each do |image| %>

		<div class="col-md-4">

			<div class="panel panel-default">

				<div class="panel-heading preview">
					<image src="<%=(url_for(image))%>", width="100%"></image>
				</div>

				<div class="panel-body">
					<span class="pull-right">
							<%= link_to '<i class="fa fa-trash" aria-hidden="true"></i>'.html_safe, delete_image_room_path(image), method: :delete, data: {confirm: "Are you sure?"} %>
					</span>
				</div>

			</div>

		</div>

	<% end %>

</div>

app/views/rooms/_room_menu.html.erb
<ul class="sidebar-list">
	<li class="sidebar-item">
		<%= link_to "Listing", listing_room_path, class: "sidebar-link active" %>
		<span class="pull-right text-babu"><i class="fa fa-check"></i></span>
	</li>

	<li class="sidebar-item">
		<%= link_to "Pricing", pricing_room_path, class: "sidebar-link active" %>
		<% if !@room.price.blank? %>
			<span class="pull-right text-babu"><i class="fa fa-check"></i></span>
		<% end %>
	</li>

	<li class="sidebar-item">
		<%= link_to "Description", description_room_path, class: "sidebar-link active" %>
		<% if !@room.listing_name.blank? %>
			<span class="pull-right text-babu"><i class="fa fa-check"></i></span>
		<% end %>
	</li>

	<li class="sidebar-item">
		<%= link_to "Photos", photo_upload_room_path, class: "sidebar-link active" %>
		<% if !@room.images.blank? %>
			<span class="pull-right text-babu"><i class="fa fa-check"></i></span>
		<% end %>
	</li>

	<li class="sidebar-item">
		<%= link_to "Amenities", amenities_room_path, class: "sidebar-link active" %>
		<span class="pull-right text-babu"><i class="fa fa-check"></i></span>
	</li>

	<li class="sidebar-item">
		<%= link_to "Location", location_room_path, class: "sidebar-link active" %>
		<% if !@room.address.blank? %>
			<span class="pull-right text-babu"><i class="fa fa-check"></i></span>
		<% end %>
	</li>
</ul>

<hr/>

<% is_ready = !@room.active && !@room.price.blank? && !@room.listing_name.blank? && !@room.images.blank? && !@room.address.blank? %>

<%= form_for @room do |f| %>
	<%= f.hidden_field :active, value: true %>
	<%= f.submit "Publish", id: "publish_button", class: "btn btn-normal btn-block", disabled: !is_ready %>
<% end %>

app/views/rooms/amenities.html.erb
<div class="row">
	<div class="col-md-3">
		<%= render 'room_menu' %>
	</div>
	<div class="col-md-9">
		<div class="panel panel-default">
			<div class="panel-heading">
				Amenities
			</div>
			<div class="panel-body">
				<div class="container">
					<%= form_for @room do |f| %>

						<div class="row form-group">
							<div class="col-md-4">
								<%= f.check_box :is_tv %> TV
							</div>
							<div class="col-md-4">
								<%= f.check_box :is_kitchen %> Kitchen
							</div>
							<div class="col-md-4">
								<%= f.check_box :is_internet %> Internet
							</div>
						</div>

						<div class="row form-group">
							<div class="col-md-4">
								<%= f.check_box :is_heating %> Heating
							</div>
							<div class="col-md-4">
								<%= f.check_box :is_air %> Air Conditioning
							</div>
						</div>
						<br/><br/>

						<div class="text-center">
							<%= f.submit "Save", class:"btn btn-form" %>
						</div>

					<% end %>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/rooms/create.html.erb
<h1>Room#create</h1>
<p>Find me in app/views/room/create.html.erb</p>

app/views/rooms/description.html.erb
<div class="row">
	<div class="col-md-3">
		<%= render 'room_menu' %>
	</div>
	<div class="col-md-9">
		<div class="panel panel-default">
			<div class="panel-heading">
				Description
			</div>
			<div class="panel-body">
				<div class="container">
					<%= form_for @room do |f| %>
						<div class="row">
							<div class="form-group">
								<label>Listing Name</label>
								<%= f.text_field :listing_name, placeholder: "What will you call your listing?", class: "form-control", required: true %>
							</div>
						</div>

						<div class="row">
							<div class="form-group">
								<label>Summary</label>
								<%= f.text_area :summary, rows: 5, placeholder: "Tell us about your listing", class: "form-control", required: true %>
							</div>
						</div>

						<div class="text-center">
							<%= f.submit "Save", class: "btn btn-form" %>
						</div>

					<% end %>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/rooms/index.html.erb
<div class="row">
	<div class="col-md-3">
		<ul class="sidebar-list">
			<li class="sidebar-item"><%= link_to "Your Listings", rooms_path, class: "sidebar-link active" %></li>
			<li class="sidebar-item"><%= link_to "Your Reservations", rooms_path, class: "sidebar-link active" %></li>
		</ul>
	</div>
	<div class="col-md-9">
		<div class="panel panel-default">
			<div class="panel-heading">
				Listings
			</div>
			<div class="panel-body">
				
				<% @rooms.each do |room| %>

						<div class="row">
							<div class="col-md-4">
								<%= image_tag room.cover_photo, height: "50px" %>
							</div>
							<div class="col-md-5">
								<h4><%= room.listing_name %></h4>
							</div>
							<div class="col-md-3 right">
								<%= link_to "Update", listing_room_path(room), class: "btn btn-form" %>
							</div>
						</div>
						<hr/>

				<% end %>

			</div>
		</div>
	</div>
</div>

app/views/rooms/listing.html.erb
<div class="row">
	<div class="col-md-3">
		<%= render 'room_menu' %>
	</div>
	<div class="col-md-9">
		<div class="panel panel-default">
			<div class="panel-heading">
				Listing
			</div>
			<div class="panel-body">
				<div class="container">
				<%= form_for @room do |f| %>
					<div class="row">
						<div class="col-md-4 select">
							<div class="form-group">
								<label>Listing Type</label>
								<%= f.select :home_type, [["Apartment", "Apartment"], ["House", "House"], ["Shit Shack", "Shit Shack"]], id: "home_type", prompt: "Select...", class: "form-control" %>
							</div>
						</div>

						<div class="col-md-4 select">
							<div class="form-group">
								<label>Room Type</label>
								<%= f.select :room_type, [["Entire", "Entire"], ["Private", "Private"], ["Shared", "Shared"]], id: "room_type", prompt: "Select...", class: "form-control" %>
							</div>
						</div>

						<div class="col-md-4 select">
							<div class="form-group">
								<label>Accommodates</label>
								<%= f.select :accomodate, [["1", 1], ["2", 2], ["3", 3]], id: "accomodate", prompt: "Select...", class: "form-control" %>
							</div>
						</div>

						<div class="col-md-4 select">
							<div class="form-group">
								<label>Bedrooms</label>
								<%= f.select :bed_room, [["1", 1], ["2", 2], ["3", 3]], id: "bed_room", prompt: "Select...", class: "form-control" %>
							</div>
						</div>

						<div class="col-md-4 select">
							<div class="form-group">
								<label>Bathrooms</label>
								<%= f.select :bath_room, [["1", 1], ["2", 2], ["3", 3]], id: "bath_room", prompt: "Select...", class: "form-control" %>
							</div>
						</div>

					</div>

					<div>
						<%= f.submit "Save", class: "btn btn-normal" %>
					</div>
				<% end %>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/rooms/location.html.erb
<div class="row">
	<div class="col-md-3">
		<%= render 'room_menu' %>
	</div>
	<div class="col-md-9">
		<div class="panel panel-default">
			<div class="panel-heading">
				Location
			</div>
			<div class="panel-body">
				<div class="container">

					<%= form_for @room do |f| %>
						<div class="row">
							<div class="form-group">
								<label>Location</label>
								<%= f.text_field :address, placeholder: "What is your address?", class: "form-control" %>
							</div>
						</div>

						<div class="text-center">
							<%= f.submit "Save", class: "btn btn-form" %>
						</div>

					<% end %>

				</div>
			</div>
		</div>
	</div>
</div>

app/views/rooms/new.html.erb
<div class="panel panel-default">
	<div class="panel-heading">
		Create your listing
	</div>
	<div class="panel-body">
		<div class="container">
			<%= form_for @room do |f| %>
				<div class="row">
					<div class="col-md-4 select">
						<div class="form-group">
							<label>Listing Type</label>
							<%= f.select :home_type, [["Apartment", "Apartment"], ["House", "House"], ["Shit Shack", "Shit Shack"]], id: "home_type", prompt: "Select...", class: "form-control" %>
						</div>
					</div>

					<div class="col-md-4 select">
						<div class="form-group">
							<label>Room Type</label>
							<%= f.select :room_type, [["Entire", "Entire"], ["Private", "Private"], ["Shared", "Shared"]], id: "room_type", prompt: "Select...", class: "form-control" %>
						</div>
					</div>

					<div class="col-md-4 select">
						<div class="form-group">
							<label>Accommodates</label>
							<%= f.select :accomodate, [["1", 1], ["2", 2], ["3", 3]], id: "accomodate", prompt: "Select...", class: "form-control" %>
						</div>
					</div>

					<div class="col-md-4 select">
						<div class="form-group">
							<label>Bedrooms</label>
							<%= f.select :bed_room, [["1", 1], ["2", 2], ["3", 3]], id: "bed_room", prompt: "Select...", class: "form-control" %>
						</div>
					</div>

					<div class="col-md-4 select">
						<div class="form-group">
							<label>Bathrooms</label>
							<%= f.select :bath_room, [["1", 1], ["2", 2], ["3", 3]], id: "bath_room", prompt: "Select...", class: "form-control" %>
						</div>
					</div>

				</div>

				<div>
					<%= f.submit "Create My Listing", class: "btn btn-normal" %>
				</div>
			<% end %>
		</div>
	</div>
</div>

app/views/rooms/photo_upload.html.erb
<div class="row">
	<div class="col-md-3">
		<%= render 'room_menu' %>
	</div>
	<div class="col-md-9">
		<div class="panel panel-default">
			<div class="panel-heading">
				Photos
			</div>
			<div class="panel-body">
				<div class="container">
					<div class="row">
						<div class="col-md-offset-3 col-md-6">
							<%= form_for @room do |f| %>
								<div class="form-group">
						        <%= f.label "Upload Photos of Your Listing" %>
						        <%= f.file_field :images, multiple: true, class: "form-control", placeholder: "Upload Photos", required: true %>
						    	</div>
						    	<div class="actions">
							      <%= f.submit "Update", class: "btn btn-normal btn-block" %>
							    </div>
					    	<% end %>
						</div>
					</div>
					<div class="row">
						<% if @room.images.attached? %>
							<div id="photos"><%= render "photos_list" %></div>
						<% else %>
							<h2>Please upload images</h2>
						<% end %>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/rooms/pricing.html.erb
<div class="row">
	<div class="col-md-3">
		<%= render 'room_menu' %>
	</div>
	<div class="col-md-9">
		<div class="panel panel-default">
			<div class="panel-heading">
				Pricing
			</div>
			<div class="panel-body">
				<div class="container">
					<%= form_for @room do |f| %>
						<div class="row">
							<div class="form-group">
								<label>Price</label>
								<%= f.text_field :price, placeholder: "i.e. $100/night", class: "form-control", required: true %>
							</div>
						</div>

						<div class="text-center">
							<%= f.submit "Save", class: "btn btn-form" %>
						</div>

					<% end %>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/rooms/show.html.erb
<!-- Image -->
<div class="row">
	<div class="col-md-12">
		<%= image_tag @room.cover_photo, width: "100%" %>
	</div>
</div>
<br/>

<div class="row">
	
	<div class="col-md-4">
	<!-- Reservation Form -->
		<%= render 'reservations/form' %>
	</div>
	<!-- LEFT PANEL -->
	<div class="col-md-8">

		<!-- LISTING NAME -->
		<div class="row">
			<div class="col-md-8">
				<h1><%= @room.listing_name %></h1>
				<%= @room.address %>
			</div>
			<div class="col-md-4 text-center">
				<image src="<%=(url_for(@room.user.image))%>", class="img-circle avatar_med"><br/><br/>
				<%= @room.user.fullname %>
			</div>
		</div>
		<hr/>

		<!-- ROOM INFO -->
		<div class="row text-babu">
			<div class="row text-center row-space-1">
				<div class="col-md-3">
					<i class="fa fa-home fa-2x"></i>
				</div>
				<div class="col-md-3">
					<i class="fa fa-user-circle-o fa-2x"></i>
				</div>
				<div class="col-md-3">
					<i class="fa fa-bed fa-2x"></i>
				</div>
				<div class="col-md-3">
					<i class="fa fa-bath fa-2x"></i>
				</div>
			</div>

			<div class="row text-center">
				<div class="col-md-3"><%= @room.home_type %></div>
				<div class="col-md-3"><%= pluralize(@room.accomodate, "Guest") %></div>
				<div class="col-md-3"><%= pluralize(@room.bed_room, "Bedroom") %></div>
				<div class="col-md-3"><%= pluralize(@room.bath_room, "Bathroom") %></div>
			</div>
		</div>
		<hr/>

		<!-- ABOUT -->
		<div class="row">
			<div class="col-md-12">
				<h3>About This Listing</h3>
				<p><%= @room.summary %></p>
			</div>
		</div>
		<hr/>

		<!-- AMENITIES -->
		<div class="row">
			<div class="col-md-3">
				<h4>Amenities</h4>
			</div>
			
			<div class="col-md-9">
				<div class="row">
					<div class="col-md-6">
						<ul class="amenities">
							<li class="<%= 'text-line-through' if !@room.is_tv %>">TV</li>
							<li class="<%= 'text-line-through' if !@room.is_kitchen %>">Kitchen</li>
							<li class="<%= 'text-line-through' if !@room.is_internet %>">Internet</li>
						</ul>
					</div>
					<div class="col-md-6">
						<ul class="amenities">
							<li class="<%= 'text-line-through' if !@room.is_heating %>">Heating</li>
							<li class="<%= 'text-line-through' if !@room.is_air %>">Air Conditioning</li>
						</ul>
					</div>
				</div>
			</div>
		</div>
		<hr/>

		<!-- CAROUSEL -->
		<div class="row">

		<% if @room.images.length > 1 %>

			<div id="myCarousel" class="carousel slide" data-ride="carousel">
			  <!-- Indicators -->
			  <ol class="carousel-indicators">
			  	<% @room.images.each do |image| %>
			    	<li data-target="#myCarousel" data-slide-to="<%= image.id %>" class="active"></li>
			    <% end %>
			  </ol>

			  <!-- Wrapper for slides -->
			  <div class="carousel-inner">
				<% @room.images.each do |image| %>
				    <div class="item <%= 'active' if image.id == @room.images[0].id %>">
				      <image src="<%=(url_for(image))%>", height="100px">
				    </div>
			    <% end %>
			  </div>

			  <!-- Left and right controls -->
			  <a class="left carousel-control" href="#myCarousel" data-slide="prev">
			    <span class="glyphicon glyphicon-chevron-left"></span>
			    <span class="sr-only">Previous</span>
			  </a>
			  <a class="right carousel-control" href="#myCarousel" data-slide="next">
			    <span class="glyphicon glyphicon-chevron-right"></span>
			    <span class="sr-only">Next</span>
			  </a>
			</div>
		</div>
		<hr/>
		<% end %>

		<!-- GOOGLE MAPS -->
		<div class="row">
			<div id="map" style="width: 100%; height: 400px"></div>

			<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyB6__tulLBc-nGutfvSo6w6OrYrjNFZ-9o&callback=initMap" async defer></script>
			<script>
				function initialize() {
					var location = {lat: <%= @room.latitude %>, lng: <%= @room.longitude %>};
					var map = new google.maps.Map(document.getElementById('map'), {
						center: location,
						zoom: 14
					});

					var marker = new google.maps.Marker({
						position: location,
						map: map
					});

					var infoWindow = new google.maps.InfoWindow({
						content: '<div id="content" class="image-circle avatar_med"><%= image_tag @room.user.image %></div>'
					});

					infoWindow.open(map, marker);
				}

				google.maps.event.addDomListener(window, 'load', initialize);
			</script>
		</div>

		<!-- NEARBY LISTINGS -->
		<div class="row">
			<h3>Near by</h3>
			<% for room in @room.nearbys(10) %>

				<div class="col-md-4">
					<div class="panel panel-default">
						<div class="panel-heading">
							<%= image_tag room.cover_photo, width: "100%" %>
						</div>
						<div class="panel-body">
							<%= link_to room.listing_name, room %><br/>
							(<%= room.distance.round(2) %> miles away)
						</div>
					</div>
				</div>

			<% end %>
		</div>

	</div>

	<!-- RIGHT PANEL -->

</div>

app/views/rooms/update.html.erb
<h1>Room#update</h1>
<p>Find me in app/views/room/update.html.erb</p>

app/views/shared/_devisemes.html.erb
<% unless resource.errors.empty? %>
	<script type="text/javascript">
		<% resource.errors.full_messages.each do |value| %>
			toastr.error('<%= value %>')
		<% end %>
	</script>
<% end %>

app/views/shared/_message.html.erb
<% unless flash.empty? %>
	<script type="text/javascript">
		<% flash.each do |key, value| %>
			<% type = key.to_s.gsub('alert','error').gsub('notice','success') %>
			toastr['<%= type %>']('<%= value %>')
		<% end %>
	</script>
<% end %>